### ISSUE TITLE
[Bug] Chinese Input bugs in Fcitx5-chewing and Wayland

### ISSUE THREAD

**Issue by tobiichi3227** [AppFlowy-IO/AppFlowy#2459]
### Bug Description

When I typing Chinese by using Fcitx5, the previous typed text were replaced by now typed.
And when end of typing, the text length became twice

### How to Reproduce

Using Fcitx5 input method

### Expected Behavior

Like typing in English 

### Operating System

Arch Linux

### AppFlowy Version(s)

0.1.4

### Screenshots

![input](https://user-images.githubusercontent.com/86729076/236369480-8c8795e1-f18f-4675-ac0a-673e58e5ac12.gif)

### Additional Context

I am using Wayland, and I didn't test this bug in Xorg
Maybe Xorg didn't have this bug

**Comment by annieappflowy** [comment]
https://github.com/flutter/flutter/issues/113909#issuecomment-1311478223
This is a known issue

**Comment by annieappflowy** [comment]
Should be fixed in the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases). Let us know if it doesn't work for you
<img width="224" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/46277bf9-3fd0-4b0c-9fc8-1333d17e9a97">

**Comment by Crany-web** [comment]
Samuti ilmnes viga Fcitx5 kasutamisel hiina keele sisestamiseks, kui kasutasin AppFlowy uusimat versiooni AUR-i hoidlas. Kasutan X11.
<img href="https://raw.githubusercontent.com/Crany-web/log/main/AppFlowy.gif" />

**Comment by nyacat** [comment]
I have same issue as https://github.com/AppFlowy-IO/AppFlowy/issues/2459#issuecomment-1854192004

**Comment by XGX1** [comment]
This problem still exists and can still be reproduced in wayland

**Comment by XGX1** [comment]
我不知道keyboard_service_widget.dart文件修改的作用，我的参考：https://github.com/AppFlowy-IO/AppFlowy/commit/f5cc6521fbcad8564c7193b705a5e5429b6d8e82
delta_input_on_replace_impl.dart内如果replacement开头出现空行，则无法正常处理输入法，但是replacement在non_delta_input_service.dart的apply方法内执行了format方法，导致无法在delta_input_on_replace_impl.dart内判断开头时是否是空格
但是用方向键移动插入指针到前面的字符不会产生响应，就像我下面这个视频展示的一样

但我不懂dart和flutter,不知如何修复，并且delta_input_on_replace_impl.dart的修复一定不符合规范和运行逻辑，我希望能帮我修好。

https://github.com/AppFlowy-IO/AppFlowy/assets/31309149/b44039f7-c26e-49bf-a8a5-0c96e48ac3ec


这是我的修改：[068b7948ab8380f3c7ef655f9891a4f92a8ba518](https://github.com/XGX1/appflowy-editor/commit/068b7948ab8380f3c7ef655f9891a4f92a8ba518)

可以的话我希望能修复输入问题，插入指针移动问题需要修复的话，也可以联系我，我能够提供测试设备和环境。

修复fcitx5和wayland下无法输入中文问题

我的英文不好，用中文回答了十分抱歉。

**Comment by LucasXu0** [comment]
@XGX1 Really appreciate your testing and help. I'll try your changes and see if I can fix it on Linux as soon as possible.

**Comment by Eason0729** [comment]
This issue still exist, is there anyone working on this now?

**Comment by PeterWang-dev** [comment]
Problem still exists. Any one working on it?
