### ISSUE TITLE
[Bug] cursor position

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2857]
### Bug Description

![Untitled video](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/0d608b3a-99ed-4ea5-ad93-77f2da95e1ce)

### How to Reproduce

ctrl + shift + > to select the sentence
press the down arrow

### Expected Behavior

un-select the text
the cursor is in the beginning of the next line (block) if there isn't another non-empty line
the cursor is in the end of the next text block if there is another non-empty line

FYI: check how google docs handles it

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.2

**Comment by Xazin** [comment]
This seems to have been resolved somewhere between 0.2.3 and 0.3.2, at least it seems to work correctly for me 0.3.2

Can you double check @annieappflowy ?

_In debug mode it seems the cursor is updated twice though, which shouldn't happen, it flickers to start/end of line depending on direction of selection._

**Comment by rileyhawk1417** [comment]
https://github.com/user-attachments/assets/8a443efd-3a23-4e78-b0ae-25ff34696bc3

`ctrl+shift+left_arrow` works fine not sure about the "press down arrow" behavior unless they meant `ctrl + down_arrow`?

@Xazin since 0.8.2 is out I dont think this issue is still there is it?
