### ISSUE TITLE
[Bug] One specific page will not load.

### ISSUE THREAD

**Issue by levidoughty** [AppFlowy-IO/AppFlowy#4838]
### Bug Description

I am unsure if this issue is worth reporting, but I will do it anyway, in case anyone else has it. I created a specific page on my desktop PC using the AppFlowy Windows app. I am using AppFlowy Cloud to sync my pages between my PC, laptop, and phone. I can access all my pages across my devices, except for one specific page. I can access the page on the device it was created on, my Windows 10 PC, but I am unable to access it on my laptop on Windows 11, or my iPhone.

It says on my Windows 11 laptop:
```
AppFlowy Error
msg:NoRequiredData
```

It says on my iPhone on iOS 17.3.1:
```
AppFlowy Error
code: InvalidParams
msg: NoRequiredData
```

### How to Reproduce

I am not entirely sure what caused this particular issue. I simply created a page on my Windows 10 PC, and for some reason, this specific page cannot be accessed on my other devices. I have not checked if the issue persists on Linux yet, but I can check that. I am using Discord for my AppFlowy Cloud account.

### Expected Behavior

I expected to be able to access and edit my page from my other devices.

I can access the page on the device it was created on, but not my other devices.

### Operating System

Windows 11 Pro & iOS 17.3.1

### AppFlowy Version(s)

AppFlowy 0.3.9.1 on Windows 11, AppFlowy 0.5.0 (3) on iOS (TestFlight)

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/66757903/1e439090-827b-4ea3-9c40-744073c3a089)
![appflowy error ios](https://github.com/AppFlowy-IO/AppFlowy/assets/66757903/fabc2dd4-8bef-4f43-b3db-e11de166f751)

### Additional Context

I have not seen this issue with any of the other pages I have created, regardless of the device I created the page on. I apologize if this issue would be better sorted out on Discord, I can direct my attention there if you feel this is something we can simply discuss on there.

**Comment by appflowy** [comment]
@levidoughty We're releasing a new version soon that fixes the crash issue on Windows. Once it's out, please use the latest version for testing. The problem should be resolved.

**Comment by annieappflowy** [comment]
Hi @levidoughty , do you encounter the same issue with v0.5.3?

**Comment by levidoughty** [comment]
Hi @annieappflowy , I have not yet updated AppFlowy on my Windows PC install. I did not see a way to update from within the app, would I just download the newest installer from the website and run it? I was afraid of losing this particular page, although I could always back it up and then proceed with the installation.

As of right now, I am still unable to view this particular page on my iPhone or my Windows laptop. I will eventually try it out on my Fedora installation when I get a chance.

Thank you for any support you can provide!

**Comment by levidoughty** [comment]
It appears that updating fixed the issue! I ran the Windows installer and installed in the same directory. I am now able to access that page on my iPhone. I have not yet checked my Windows laptop, but I can check that too soon! I am thinking I want to try AppFlowy on Linux so I will inform you if I have any issues with that!

**Comment by appflowy** [comment]
@levidoughty I will close this issue. Please feel free to reopen
