### ISSUE TITLE
[Bug] 0.6.1 release artifacts are zipped twice

### ISSUE THREAD

**Issue by aliesbelik** [AppFlowy-IO/AppFlowy#5623]
### Bug Description

*.zip artifacts from 0.6.1 release are zipped twice (a zip archive inside another zip archive with the same name),
i.e.
```
AppFlowy-0.6.1-windows-x86_64.zip
  AppFlowy-0.6.1-windows-x86_64.zip
    AppFlowy
      ...
AppFlowy-0.6.1-macos-x86_64.zip
  AppFlowy-0.6.1-macos-x86_64.zip
    AppFlowy.app
      ...
AppFlowy-0.6.1-macos-universal.zip
  AppFlowy-0.6.1-macos-universal.zip
    AppFlowy.app
      ...
```

Not the issue for previous releases, including 0.6.0.

### How to Reproduce

1. Go to the 0.6.1 release assests: https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.6.1.
2. Download any *.zip, e.g. https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.6.1/AppFlowy-0.6.1-windows-x86_64.zip.
3. Unpack it somewhere.

### Expected Behavior

After unpacking, one would expect to see `AppFlowy` directory containing the application files.

### Operating System

windows

### AppFlowy Version(s)

0.6.1

**Comment by aliesbelik** [comment]
Looks like there are no recent changes in release.yml that could cause that.
Similar issue reported for `upload-artifact` GH action (actions/upload-artifact#39) but as I can see it isn't used here.

**Comment by aliesbelik** [comment]
Not reproducible with 0.6.2 release *.zip packages.

**Comment by annieappflowy** [comment]
Thank you for confirming that this bug was fixed.

**Comment by aliesbelik** [comment]
Same with [0.8.0](https://github.com/AppFlowy-IO/AppFlowy/releases) release artifacts (both windows and macos zip archives).

Could you please reopen or should I raise another issue?

**Comment by LucasXu0** [comment]
@aliesbelik These packages were compressed twice during the CI tasks. I've removed the duplicate zip. May I know if there is any GitHub Action provided by `ScoopInstaller` to check the `Extra`?

**Comment by charleslales** [comment]
Thanks for fixing, still an issue:

Checking hash of AppFlowy-0.8.0-windows-x86_64.zip ... ERROR Hash check failed!
App:         extras/appflowy
URL:         https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.8.0/AppFlowy-0.8.0-windows-x86_64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    091a627337ae031eec86e0e29b88401aa0c58ce63e15eb47e0f84375e66cfb12
Actual:      c17546531633aa91ce99b28251f21e3b000ac5252e72b63a78c0dd3e10d8c0ca

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=appflowy%400.8.0%3a+hash+check+failed

**Comment by aliesbelik** [comment]
@LucasXu0 Thank you for quick reaction. I've updated and tested manifest manually, should be ok now.

**Comment by charleslales** [comment]
thanks to you! working fine ;-)
