### ISSUE TITLE
[Bug] Kanban board bug (AKA picky magnifying bug)

### ISSUE THREAD

**Issue by unknoxx** [AppFlowy-IO/AppFlowy#5915]
### Bug Description

I don't even know what to call this bug, The Kanban board on one  of my spaces is a picky bug, if the board isn't on "Done" and I hover my mouse on the page there is this bug (as shown in the image)

### How to Reproduce

1. Open a space 
2. Open an existing board
3. Hover on the page where the board is especially if it's not on "Done" 
4. And the bug is just like the screenshot except if it's on done 

### Expected Behavior

Work normally

### Operating System

Ubuntu Budgie 22.04.4 LTS x86_64

### AppFlowy Version(s)

0.6.6

### Screenshots

![Screenshot from 2024-08-09 17-37-19](https://github.com/user-attachments/assets/4fd36bf9-89f0-448f-b861-ade9e1c23d04)

**if  board isn't on done :**

![Screenshot from 2024-08-09 17-36-59](https://github.com/user-attachments/assets/b99c66cb-bf0f-451e-a33c-af0e1e138a65)

**Comment by dungeon-slave** [comment]
Have similar issue sometimes using Linux Mint 22 Wilma Ubuntu Edition with Cinnamon Environment

**Comment by unknoxx** [comment]
@dungeon-slave  Are you facing the same issue? I want to close it seems to have been fixed since the new update on 0.6.9.

**Comment by dungeon-slave** [comment]
> @dungeon-slave  Are you facing the same issue? I want to close it seems to have been fixed since the new update on 0.6.9.

i can't definetely say, because didn't use 0.6.9 on my Linux Mint yet. Can provide you this info on next week.

**Comment by unknoxx** [comment]
Sure! Let me know so I can decide if closing this issue is needed or not

**Comment by dungeon-slave** [comment]
Unfortunately, i still facing this issue on my system. My version is 0.6.9
![image](https://github.com/user-attachments/assets/a8d9bf92-5391-48d3-85f4-4e4f5e9d54b5)

**Comment by unknoxx** [comment]
> Unfortunately, i still facing this issue on my system. My version is 0.6.9 ![image](https://private-user-images.githubusercontent.com/70040363/369628964-a8d9bf92-5391-48d3-85f4-4e4f5e9d54b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NTA5OTQsIm5iZiI6MTcyNjk1MDY5NCwicGF0aCI6Ii83MDA0MDM2My8zNjk2Mjg5NjQtYThkOWJmOTItNTM5MS00OGQzLTg1ZjQtNGU0ZjVlOWQ1NGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDIwMzEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMWJhNzMyMDhlYmQyM2YyYTA3MDRlM2JkMTEzYjg0MGM0ZTJiNjA5MDNjNjdhNmE0ZWZjYjBlNjE3YTdmODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eT2C4bd9jHXsuoZTBYjRtJLjJICOHhO5jMJsLzvLtWc)

@annieappflowy
